app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'FrontController@index');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::resource('usuario','UsuarioController');

Route::get('/trash/{id}',[
    'as' => 'receta.trash',
    'uses' => 'recetaController@trash'
]);
Route::resource('receta/view_trash', 'recetaController@view_trash');
Route::resource('receta','recetaController');

post('/getIngrediente', 'IngredienteController@getIngrediente');
post('/addIngrediente', 'IngredienteController@addIngrediente');
post('/addProduct', 'IngredienteController@addProduct');
Route::resource('ingrediente','IngredienteController');

Route::resource('log','LogController');
Route::post('/password/correo-de-recuperacion',[
    'as' => 'log.recover',
    'uses' => 'LogController@recover'
]);

Route::get('admin', 'FrontController@admin');

Route::get('logout', 'LogController@logout');


post('/getParam', 'ParametroController@getParam');
Route::resource('parametro','ParametroController');

Route::resource('insumo','InsumoController');

Route::resource('insumousado','InsumoUsadoController');

post('/storeSalario', 'SalarioController@storeSalario');
Route::resource('salario','SalarioController');

post('/getProveedor', 'ProveedorController@getProveedor');
post('/searchProveedor', 'ProveedorController@searchProveedor');
post('/storeProveedor', 'ProveedorController@storeProveedor');
Route::resource('proveedor','ProveedorController');

Route::get('/compra/trash/{id}',[
    'as' => 'compra.trash',
    'uses' => 'CompraController@trash'
]);
Route::resource('compra/view_trash', 'CompraController@view_trash');
Route::post('/compra/pass',[
    'as' => 'compra.pass',
    'uses' => 'CompraController@pass'
]);
Route::get('/compra/reporte/{factura_o_mensual}/{fecha?}/{factura?}',[
    'as' => 'compra.reporte',
    'uses' => 'CompraController@reporte'
]);

post('/checkCode', 'CompraController@checkCode');
post('/createParam', 'CompraController@createParam');
Route::resource('compra','CompraController');

post('/createMP', 'MateriaPrimaController@createMP');
Route::resource('materiaprima/insert', 'MateriaPrimaController@insert');
/*
Route::get('/materiaprima/reporte/{fecha_caja}',[
    'as' => 'materiaprima.reporte',
    'uses' => 'MateriaPrimaController@reporte'
]);
*/
Route::resource('materiaprima', 'MateriaPrimaController');

/*
Route::get('/listCardexMP', 'CardexMPController@listCardexMP');
Route::get('/listCardexPA', 'CardexMPController@listCardexPA');
Route::get('/listCardexPB', 'CardexMPController@listCardexPB');
Route::get('/listCardexPC', 'CardexMPController@listCardexPC');
*/
Route::resource('cardexMP', 'CardexMPController');
Route::get('/cardex/reporte/{fecha}/{item}',[
    'as' => 'cardexmp.reporte',
    'uses' => 'CardexMPController@reporte'
]);


Route::get('/InventarioPA', 'InventarioController@InventarioPA');
Route::get('/InventarioPB', 'InventarioController@InventarioPB');
Route::get('/InventarioPC', 'InventarioController@InventarioPC');

Route::get('/inventario/reporte/{fecha_caja}/{inventario}',[
    'as' => 'inventario.reporte',
    'uses' => 'InventarioController@reporte'
]);
Route::get('/cardexProduccion/reporte/{fecha}/{etapa}/{receta}',[
    'as' => 'produccion.reporteCardex',
    'uses' => 'ProduccionController@reporteCardex'
]);

post('/guardarCostos', 'ProduccionController@guardarCostos');

Route::resource('produccion/{prod}/insert', 'ProduccionController@insert');
Route::post('adjust',[
    'as' => 'produccion.adjust',
    'uses' => 'ProduccionController@adjust'
]);
Route::get('produccion/{id}/create', 'ProduccionController@createProd');
Route::post('pass',[
    'as' => 'produccion.pass',
    'uses' => 'ProduccionController@pass'
]);
post('/reqDepUpd', 'ProduccionController@reqDepUpd');
post('/reqUpd', 'ProduccionController@req_upd');
post('/checkDep', 'ProduccionController@checkDep');
post('/storeProd', 'ProduccionController@storeProd');
Route::get('/verProduccion/{id}', 'ProduccionController@verProduccion');
Route::get('/Producciones/reporte/{fecha}',[
    'as' => 'producciones.reporte',
    'uses' => 'ProduccionController@reporte'
]);
Route::get('/Produccion/reporte/{id}',[
    'as' => 'produccion.reporte',
    'uses' => 'ProduccionController@reporteProduccion'
]);
Route::resource('produccion','ProduccionController');


post('/addDependencia', 'DependenciaController@addDependencia');
Route::resource('dependencia','DependenciaController');

Route::resource('aumento','AumentoController');

Route::resource('miscelaneo','MiscelaneoController');

Route::resource('costofijo','CostoFijoController');

Route::resource('produccionmes','ProduccionmesController');

Route::get('cuentaxpagar/view/{id}',[
    'as' => 'cuentaxpagar.view',
    'uses' => 'CtaxPagarController@view'
]);
Route::resource('cuentaxpagar','CtaxPagarController');

Route::get('cuentaxcobrar/view/{id}',[
    'as' => 'cuentaxcobrar.view',
    'uses' => 'CtaxCobrarController@view'
]);
Route::resource('cuentaxcobrar','CtaxCobrarController');

Route::post('caja/abrir',[
    'as' => 'caja.abrir',
    'uses' => 'CajaBancoController@abrir'
]);
Route::get('caja/volverfecha/{entidad}',[
    'as' => 'caja.volverfecha',
    'uses' => 'CajaBancoController@volverfecha'
]);
Route::get('caja/cerrar/{entidad}/{fecha}', [
	'as' => 'caja.cerrarcaja',
	'uses' => 'CajaBancoController@cerrarcaja'
]);
Route::get('caja/confirmar/{entidad}/{fecha}', [
	'as' => 'caja.confirmarcierre',
	'uses' => 'CajaBancoController@confirmarcierre'
]);
Route::get('caja/cierre/{entidad}/{fecha}', [
	'as' => 'caja.vercierre',
	'uses' => 'CajaBancoController@vercierre'
]);
Route::get('caja/reporte/{entidad}/{fecha}', [
	'as' => 'caja.reporte',
	'uses' => 'CajaBancoController@reporte'
]);
Route::get('caja/transferir/{entidad}/{fecha}', [
    'as' => 'caja.transferir',
    'uses' => 'CajaBancoController@transferir'
]);
Route::post('maketransfer',[
    'as' => 'caja.maketransfer',
    'uses' => 'CajaBancoController@maketransfer'
]);
Route::get('caja/entradaForm/{entidad}/{fecha}', [
    'as' => 'caja.entradaForm',
    'uses' => 'CajaBancoController@entradaForm'
]);
Route::get('caja/salidaForm/{entidad}/{fecha}', [
    'as' => 'caja.salidaForm',
    'uses' => 'CajaBancoController@salidaForm'
]);
Route::post('caja/generarEntrada', [
    'as' => 'caja.generarEntrada',
    'uses' => 'CajaBancoController@generarEntrada'
]);
Route::post('caja/generarSalida', [
    'as' => 'caja.generarSalida',
    'uses' => 'CajaBancoController@generarSalida'
]);
Route::resource('caja','CajaBancoController');
post('/getDisponible', 'CajaBancoController@getDisponible');
Route::post('venta/facturar', [
    'as' => 'venta.facturar',
    'uses' => 'VentaController@facturar'
]);
Route::get('venta/revertir/{factura}', [
    'as' => 'venta.revertir',
    'uses' => 'VentaController@revertir'
]);
Route::get('/venta/reporte/{factura_o_mensual}/{atributo}',[
    'as' => 'venta.reporte',
    'uses' => 'VentaController@reporte'
]);
Route::resource('venta','VentaController');

Route::resource('cliente','ClienteController');

Route::resource('banco','BancoController');

Route::post('ajustes/reiniciar-base-de-datos', [
    'as' => 'ajustes.reiniciarDB',
    'uses' => 'AjusteController@reiniciarDB'
]);
Route::post('ajustes/iniciar', [
    'as' => 'ajustes.iniciar',
    'uses' => 'AjusteController@iniciar'
]);
Route::get('ajustes/inventario/{target}/{id}', [
    'as' => 'ajustes.inventario',
    'uses' => 'AjusteController@inventario'
]);
Route::post('ajustes/setinventario', [
    'as' => 'ajustes.setinventario',
    'uses' => 'AjusteController@setinventario'
]);
Route::resource('ajustes','AjusteController');

resources/views/caja/ajustar.blade.php
@extends('layouts.admin')

@section('content')
	@include('alerts.success')
	{!!Form::open(['route'=>'caja.store','method'=>'POST'])!!}
	<div class="row margenBotLg">
		<div class="col-md-12">
			
			<h3>Seleccione cual saldo quiere actualizar e ingrese su valor.</h3>
		</div>
	</div>
	<div class="row margenBotLg">
		<div class="col-md-12">
			<div class="col-md-5 col-xs-12">		    
				{!!Form::select('entidad', ['Caja Chica' => 'Caja Chica', 'Banco De Venezuela' => 'Banco De Venezuela', 'Banco Provincial' => 'Banco Provincial', 'Banco Banesco' => 'Banco Banesco', 'Banco Mercantil' => 'Banco Mercantil'], null, ['class'=>'form-control','placeholder' => 'Escoje cual saldo actualizar...'])!!}
			</div>	
			<div class="col-md-5 col-xs-12">		    
				{!!Form::text('valor', null, ['class'=>'form-control','placeholder' => 'Ingrese el saldo aquí'])!!}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-5 col-xs-12">		
			{!!Form::submit('Actualizar',['class'=>'btn btn-lg btn-success'])!!}
			</div>
			
			<input type="hidden" name="s_cajachica" id="s_cajachica" value="{{$s_cajachica}}">	 
			<input type="hidden" name="s_venezuela" id="s_venezuela" value="{{$s_venezuela}}">
			<input type="hidden" name="s_provincial" id="s_provincial" value="{{$s_provincial}}">
			<input type="hidden" name="s_banesco" id="s_banesco" value="{{$s_banesco}}">
			<input type="hidden" name="s_mercantil" id="s_mercantil" value="{{$s_mercantil}}">	 
		</div>
	</div>
	{!!Form::close()!!}
	{!!Html::script('js/jquery.min.js')!!}
	<script type="text/javascript">
		$(document).ready(function() {
			$('select[name=entidad]').change(function(){	      
				var entidad = $(this).val();
				if(entidad == 'Caja Chica'){
					var valor = $('#s_cajachica').val();
					$('input[name=valor]').val(valor);
				}else if(entidad == 'Banco De Venezuela'){
					var valor = $('#s_venezuela').val();
					$('input[name=valor]').val(valor);
				}else if(entidad == 'Banco Provincial'){
					var valor = $('#s_provincial').val();
					$('input[name=valor]').val(valor);
				}else if(entidad == 'Banco Banesco'){
					var valor = $('#s_banesco').val();
					$('input[name=valor]').val(valor);
				}else if(entidad == 'Banco Mercantil'){
					var valor = $('#s_mercantil').val();
					$('input[name=valor]').val(valor);
				}
			});
		});
	</script>	
		
		
	
@endsection

resources/views/caja/caja-report.blade.php
<!-- pdf.blade.php -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <script type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/estilosPersonalizados.css">
    </head>
    <body>
        <img src="img/gavcalogo.png" alt="logo de la empresa" style="display: inline-block;">
        <h3  style="display: inline-block; vertical-align: middle; margin-left: 5px;">
        <?php
            $time = strtotime($records[0]->cb_fecha);
            $date = date('Y-m-d',$time);
            if($caja == "")
                $caja = "Caja Chica";
        ?>
        Reporte de {{$caja}} de fecha {{$date}}</h3>
        <table class="table table-bordered">
            <tr>             
                <td>Concepto</td>
                <td align="right">Debe</td>              
                <td align="right">Haber</td>
                <td align="right">Saldo</td>
            </tr>
            <?php $t_sale = 0; $t_entra = 0; $t_saldo = 0; ?>
            @foreach($records as $record)
            <tr>
                <td>{{$record->cb_concepto}}</td>
                <?php 
                //sobreescribo el saldo xq me interesa el ultimo valor q se escriba
                $t_saldo = $record->cb_saldo;
                if($record->cb_debe_haber == "DEBE"){
                    $t_entra += $record->cb_monto;
                    echo '<td align="right">'.number_format ( $record->cb_monto , $decimals = 2 , "," , "." ).'</td><td></td>';
                }else if($record->cb_debe_haber == "HABER" && $record->cb_concepto == "Inicio de caja"){
                    echo '<td></td><td align="right">'.number_format ( $record->cb_monto , $decimals = 2 , "," , "." ).'</td>';
                }else{
                    $t_sale += $record->cb_monto;
                    echo '<td></td><td align="right">'.number_format ( $record->cb_monto , $decimals = 2 , "," , "." ).'</td>';
                }
                ?>

                <td align="right"><?php echo number_format ( $record->cb_saldo , $decimals = 2 , "," , "." ); ?></td>              
            </tr>
            @endforeach 
            <tr>
                <td><b>TOTAL</b></td>
                <td align="right"><b><?php echo number_format ( $t_entra , $decimals = 2 , "," , "." ); ?></b></td>
                <td align="right"><b><?php echo number_format ( $t_sale , $decimals = 2 , "," , "." ); ?></b></td>
                <td align="right"><b><?php echo number_format ( $t_saldo , $decimals = 2 , "," , "." ); ?></b></td>
            </tr>
        </table>
     <script src="js/jquery.min.js"></script> 
     <script src="js/bootstrap.min.js"></script> 
    </body>
</html>

resources/views/caja/caja.blade.php
@extends('layouts.admin')

@section('content')
	@include('alerts.success')
		<nav class="navbar navbar-default">
			<div class="container-fluid">
			    <div class="navbar-header">
			      	<a class="navbar-brand" href="#">Caja Banco</a>
			    </div>
			    <ul class="nav navbar-nav">
			    	<?php if($caja == ""){ $caja = "Caja Chica";?>

			    		<li class="active">{!!link_to_route('caja.show', $title = 'Caja Chica', $parameters = 'Caja Chica')!!}</li>

			    	<?php }else { ?>

			        	<li>{!!link_to_route('caja.show', $title = 'Caja Chica', $parameters = 'Caja Chica')!!}</li>

			        <?php } ?>
			        
			    	@foreach($bancos as $banco)

			    	<?php if($caja == $banco->ban_nombre){ ?>

			    		<li class="active">{!!link_to_route('caja.show', $title = $banco->ban_nombre, $parameters = $banco->ban_nombre)!!}</li>

			    	<?php }else { ?>

			        	<li>{!!link_to_route('caja.show', $title = $banco->ban_nombre, $parameters = $banco->ban_nombre)!!}</li>

			        <?php } ?>

			    	@endforeach      	
			    </ul>
			</div>
		</nav>
		<?php 
		echo "<h3>".$caja." - ".date("d/m/Y", strtotime(Session::get('caja_fecha')))."</h3>";
		
		?>
		<div class="row">
			<div class="btn-group">
				<?php if($saldo_existe === null){ ?>
				<?php if(Auth::user()->privilegio == "admin" || Auth::user()->privilegio == "tipo1") { ?>
					{!!link_to_route('caja.transferir', $title = 'Transferir Saldo', $parameters = ['entidad'=>$caja,'fecha'=>Session::get('caja_fecha')], $attributes = ['class'=>'btn btn-primary btn-sm'])!!}
				<?php } ?>	
				
					<?php if(Auth::user()->privilegio == "admin") { ?>
					{!!link_to_route('caja.entradaForm', $title = 'Dar Entrada', $parameters = ['entidad'=>$caja,'fecha'=>Session::get('caja_fecha')], $attributes = ['class'=>'btn btn-primary btn-sm'])!!}
					{!!link_to_route('caja.salidaForm', $title = 'Dar Salida', $parameters = ['entidad'=>$caja,'fecha'=>Session::get('caja_fecha')], $attributes = ['class'=>'btn btn-primary btn-sm'])!!}
					<?php } ?>		

				<?php } ?>		
				
				{!!link_to_route('caja.volverfecha', $title = 'Seleccionar Fecha Diferente', $parameters = ['entidad'=>$caja], $attributes = ['class'=>'btn btn-primary btn-sm'])!!}
				
			</div>
		</div>		
		<table class="table">
			<thead>			
				<td>Concepto</td>
				<td align="center">Debe</td>				
				<td align="center">Haber</td>
				<td align="center">Saldo</td>
				<td align="center">Opciones</td>
			</thead>
			<?php $t_sale = 0; $t_entra = 0; $t_saldo = 0; ?>
			@foreach($records as $record)
			<tr>
				<td>{{$record->cb_concepto}}</td>
				<?php 
				//sobreescribo el saldo xq me interesa el ultimo valor q se escriba

				$t_saldo = $record->cb_saldo;
				if($record->cb_debe_haber == "DEBE"){
					$t_entra += $record->cb_monto;
					echo '<td align="right">'.number_format ( $record->cb_monto , $decimals = 2 , "," , "." ).'</td><td align="right"></td>';
				}else if($record->cb_debe_haber == "HABER"){
					$t_sale += $record->cb_monto;
					echo '<td align="right"></td><td align="right">'.number_format ( $record->cb_monto , $decimals = 2 , "," , "." ).'</td>';
				}
				?>				
				<td align="right">{{number_format ( $record->cb_saldo , $decimals = 2 , "," , "." )}}</td>				
				<td align="right">
					<?php if($record->cb_compra_id !== null){ ?>
					<div class="btn-group">
						<?php if($caja_actual == Session::get('caja_fecha') && $record->cb_activo != 0){ ?>
							{!!link_to_route('compra.show', $title = 'Ver Factura', $parameters = $record->cb_compra_id, $attributes = ['class'=>'btn btn-primary btn-xs'])!!}		
							<?php if(Auth::user()->privilegio == "admin" && isset($ultima_v_c) && $ultima_v_c == $record->id && 0){ ?>			
								{!!link_to_route('compra.trash', $title = 'Revertir Compra', $parameters = $record->cb_compra_id, $attributes = ['class'=>'btn btn-danger btn-xs'])!!}
							<?php } ?>
						<?php } ?>
				    </div>
					<?php } ?>
					<?php if($record->cb_concepto == 'Venta'){ ?>
					<div class="btn-group">
						<?php if($caja_actual == Session::get('caja_fecha') && $record->cb_activo != 0){ ?>
							{!!link_to_route('venta.show', $title = 'Ver Factura', $parameters = $record->cb_venta_id, $attributes = ['class'=>'btn btn-success btn-xs'])!!}	
							<?php if(Auth::user()->privilegio == "admin" && isset($ultima_v_c) && $ultima_v_c == $record->id && 0){ ?>			
								{!!link_to_route('venta.revertir', $title = 'Revertir Venta', $parameters = $record->cb_venta_id, $attributes = ['class'=>'btn btn-danger btn-xs'])!!}
							<?php } ?>
						<?php } ?>
					</div>
					<?php } ?>
				</td>
			</tr>
			@endforeach	
			<tr>
				<td><b>TOTAL</b></td>
				<td align="right"><b>{{number_format ( $t_entra , $decimals = 2 , "," , "." )}}</b></td>
				<td align="right"><b>{{number_format ( $t_sale , $decimals = 2 , "," , "." )}}</b></td>
				<td align="right"><b>{{number_format ( $t_saldo , $decimals = 2 , "," , "." )}}</b></td>
				<td></td>
			</tr>		
		</table>
		
		<div class="row">			
			<div class="col-md-12">
				<?php if($saldo_existe === null){ ?>
					<?php if($caja == "Caja Chica"){ ?>
						<?php if(Auth::user()->privilegio == "admin" || Auth::user()->privilegio == "tipo1"){?>
							{!!link_to_route('caja.confirmarcierre', $title = 'Cerrar Día', $parameters = ['entidad'=>$caja,'fecha'=>Session::get('caja_fecha')], $attributes = ['class'=>'btn btn-success'])!!}
						<?php } ?>
					<?php } ?>
				<?php } else { ?>
				<h3>-- Día Cerrado --</h3>
					<h2>Este día esta cerrado, si desea ver o imprimir el cierre de caja haga click en el siguiente vínculo.</h2>
					{!!link_to_route('caja.reporte', $title = 'Generar reporte PDF', $parameters = ['entidad'=>$caja,'fecha'=>Session::get('caja_fecha')], $attributes = ['class'=>'btn btn-primary'])!!}
				<?php } ?>
			</div>
		</div>
	
@endsection

resources/views/caja/confirm.blade.php
@extends('layouts.admin')

@section('content')
	@include('alerts.success')
	<div class="row margenBotLg">
		<div class="col-md-12">
			
			<h3>Por favor, confirme que desea cerrar cuentas de fecha {{$fecha}}.</h3>
			<p>Si cierra el día de operación no podrá modificarlo luego.</p>
		</div>
	</div>
	<div class="row margenBotLg">
		<div class="col-md-12">
			<div class="col-md-3 col-xs-12">
				{!!link_to_route('caja.cerrarcaja', $title = 'Cerrar Día', $parameters = ['entidad'=>$entidad,'fecha'=>$fecha], $attributes = ['class'=>'btn btn-success'])!!}
			</div>
		</div>
	</div>
		
		
		
	
@endsection

resources/views/caja/in.blade.php
@extends('layouts.admin')
@section('content')
	@include('alerts.success')
	@include('alerts.request')
	@include('alerts.errors')
	{!!Form::open(['route'=>'caja.generarEntrada','method'=>'POST'])!!}
	<div class="row margenBotLg">
		<div class="col-md-12">
			
			<h3>Por favor, ingrese el monto que desea ingresar como entrada y su concepto.</h3>
		</div>
	</div>
	<div class="row margenBotLg">
		<div class="col-md-12">
			<div class="col-md-8 col-xs-12">		    
				{!!Form::text('concepto', null, ['class'=>'form-control','placeholder' => 'Ingrese el concepto aquí'])!!}
			</div>
			<div class="col-md-4 col-xs-12">		    
				{!!Form::number('monto', null, ['class'=>'form-control','placeholder' => 'Ingrese el monto aquí'])!!}
			</div>			
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-5 col-xs-12">		
			{!!Form::submit('Dar Entrada',['class'=>'btn btn-lg btn-success'])!!}
			</div>				 
		</div>
	</div>
	<input type="hidden" name="entidad" value="{{$entidad}}">
	<input type="hidden" name="fecha" value="{{$fecha}}">
	{!!Form::close()!!}		
	
@endsection

resources/views/caja/index.blade.php
@extends('layouts.admin')

@section('content')	
	@include('alerts.errors')
	<!-- Datepicker Files -->
    {!!Html::style('css/bootstrap-datepicker3.css')!!}
    {!!Html::style('css/bootstrap-datepicker3.css')!!}
    
	@include('alerts.success')
	{!!Form::open(['route'=>'caja.abrir','method'=>'POST'])!!}
	<div class="row">
		<div class="col-md-12 margenBotLg">
			<h3>Selecciona una fecha para abrir el día de operación. Debes seleccionar una fecha igual o anterior a la actual {{date_format(date_create($hoy),"d/m/Y")}}, sólo puedes seleccionar una fecha si el día anterior a la misma tiene sus cajas cerradas.</h3>
			<?php if($caja_actual != null){ ?>
			<h3>Actualmente hay un día abierto de fecha {{date_format(date_create($caja_actual),"d/m/Y")}}</h3>
			<?php }else if($ultima_caja != null){?>
			<h3>El último día que fue cerrado tiene fecha {{date_format(date_create($ultima_caja),"d/m/Y")}}</h3>
			<?php } ?>
		</div>		
	</div>
	<div class="row margenBotSm">    	
		<div class="col-xs-12 col-md-5">	
			{!!Form::date('caja_fecha',$caja_actual,['class'=>'form-control datepicker','placeholder'=>'Click aquí seleccionar una fecha','required'=>'required','autocomplete'=>'off'])!!}	
			<?php if(isset($entidad)){ ?>
			<input type="hidden" name="entidad" value="{{$entidad}}"> 
			<?php } ?>
		</div>		
	</div>
	{!!Form::submit('Abrir',['class'=>'btn btn-lg btn-success'])!!}
	{!!Form::close()!!}
		

	<!-- Jquery -->
    {!!Html::script('js/jquery.min.js')!!}
	<!-- Datepicker Files -->    
    {!!Html::script('js/bootstrap-datepicker.js')!!}
    <!-- Languaje -->
    {!!Html::script('locales/bootstrap-datepicker.es.min.js')!!}

<script type="text/javascript">	

	$('.datepicker').datepicker({
	    format: "yyyy-mm-dd",
	    language: "es",
	    autoclose: true
	});
</script>
		
	
@endsection

resources/views/caja/out.blade.php
@extends('layouts.admin')
@section('content')
	@include('alerts.success')
	@include('alerts.request')
	@include('alerts.errors')
	{!!Form::open(['route'=>'caja.generarSalida','method'=>'POST'])!!}
	<div class="row margenBotLg">
		<div class="col-md-12">
			
			<h3>Por favor, ingrese el monto que desea ingresar como salida y su concepto.</h3>
		</div>
	</div>
	<div class="row margenBotLg">
		<div class="col-md-12">			
			<div class="col-md-8 col-xs-12">		    
				{!!Form::text('concepto', null, ['class'=>'form-control','placeholder' => 'Ingrese el concepto aquí'])!!}
			</div>
			<div class="col-md-4 col-xs-12">		    
				{!!Form::text('monto', null, ['class'=>'form-control','placeholder' => 'Ingrese el monto aquí'])!!}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-5 col-xs-12">		
			{!!Form::submit('Dar Salida',['class'=>'btn btn-lg btn-success'])!!}
			</div>				 
		</div>
	</div>
	<input type="hidden" name="entidad" value="{{$entidad}}">
	<input type="hidden" name="fecha" value="{{$fecha}}">
	{!!Form::close()!!}		
	
@endsection

resources/views/caja/transfer.blade.php
@extends('layouts.admin')
@section('content')
	@include('alerts.success')
	@include('alerts.request')
	@include('alerts.errors')
	{!!Form::open(['route'=>'caja.maketransfer','method'=>'POST'])!!}
	<div class="row margenBotLg">
		<div class="col-md-12">
			
			<h3>Por favor, seleccione a donde quiere hacer la transferencia, ingrese un concepto y un monto.</h3>
		</div>
	</div>
	<div class="row margenBotLg">
		<div class="col-md-12">			
			<div class="col-md-4 col-xs-12">		    
				{!!Form::select('destino', $bancos, null, ['class'=>'form-control'])!!}
			</div>	
			<div class="col-md-4 col-xs-12">		    
				{!!Form::text('concepto', null, ['class'=>'form-control','placeholder' => 'Ingrese el concepto aquí'])!!}
			</div>
			<div class="col-md-4 col-xs-12">		    
				{!!Form::number('saldo', null, ['class'=>'form-control','placeholder' => 'Ingrese el monto aquí','min' => '1'])!!}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-5 col-xs-12">		
			{!!Form::submit('Transferir',['class'=>'btn btn-lg btn-success'])!!}
			</div>				 
		</div>
	</div>
	<input type="hidden" name="entidad" value="{{$entidad}}">
	<input type="hidden" name="fecha" value="{{$fecha}}">
	{!!Form::close()!!}		
	
@endsection