app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'FrontController@index');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::resource('usuario','UsuarioController');

Route::get('/trash/{id}',[
    'as' => 'receta.trash',
    'uses' => 'recetaController@trash'
]);
Route::resource('receta/view_trash', 'recetaController@view_trash');
Route::resource('receta','recetaController');

post('/getIngrediente', 'IngredienteController@getIngrediente');
post('/addIngrediente', 'IngredienteController@addIngrediente');
post('/addProduct', 'IngredienteController@addProduct');
Route::resource('ingrediente','IngredienteController');

Route::resource('log','LogController');
Route::post('/password/correo-de-recuperacion',[
    'as' => 'log.recover',
    'uses' => 'LogController@recover'
]);

Route::get('admin', 'FrontController@admin');

Route::get('logout', 'LogController@logout');


post('/getParam', 'ParametroController@getParam');
Route::resource('parametro','ParametroController');

Route::resource('insumo','InsumoController');

Route::resource('insumousado','InsumoUsadoController');

post('/storeSalario', 'SalarioController@storeSalario');
Route::resource('salario','SalarioController');

post('/getProveedor', 'ProveedorController@getProveedor');
post('/searchProveedor', 'ProveedorController@searchProveedor');
post('/storeProveedor', 'ProveedorController@storeProveedor');
Route::resource('proveedor','ProveedorController');

Route::get('/compra/trash/{id}',[
    'as' => 'compra.trash',
    'uses' => 'CompraController@trash'
]);
Route::resource('compra/view_trash', 'CompraController@view_trash');
Route::post('/compra/pass',[
    'as' => 'compra.pass',
    'uses' => 'CompraController@pass'
]);
Route::get('/compra/reporte/{factura_o_mensual}/{fecha?}/{factura?}',[
    'as' => 'compra.reporte',
    'uses' => 'CompraController@reporte'
]);

post('/checkCode', 'CompraController@checkCode');
post('/createParam', 'CompraController@createParam');
Route::resource('compra','CompraController');

post('/createMP', 'MateriaPrimaController@createMP');
Route::resource('materiaprima/insert', 'MateriaPrimaController@insert');
/*
Route::get('/materiaprima/reporte/{fecha_caja}',[
    'as' => 'materiaprima.reporte',
    'uses' => 'MateriaPrimaController@reporte'
]);
*/
Route::resource('materiaprima', 'MateriaPrimaController');

/*
Route::get('/listCardexMP', 'CardexMPController@listCardexMP');
Route::get('/listCardexPA', 'CardexMPController@listCardexPA');
Route::get('/listCardexPB', 'CardexMPController@listCardexPB');
Route::get('/listCardexPC', 'CardexMPController@listCardexPC');
*/
Route::resource('cardexMP', 'CardexMPController');
Route::get('/cardex/reporte/{fecha}/{item}',[
    'as' => 'cardexmp.reporte',
    'uses' => 'CardexMPController@reporte'
]);


Route::get('/InventarioPA', 'InventarioController@InventarioPA');
Route::get('/InventarioPB', 'InventarioController@InventarioPB');
Route::get('/InventarioPC', 'InventarioController@InventarioPC');

Route::get('/inventario/reporte/{fecha_caja}/{inventario}',[
    'as' => 'inventario.reporte',
    'uses' => 'InventarioController@reporte'
]);
Route::get('/cardexProduccion/reporte/{fecha}/{etapa}/{receta}',[
    'as' => 'produccion.reporteCardex',
    'uses' => 'ProduccionController@reporteCardex'
]);

post('/guardarCostos', 'ProduccionController@guardarCostos');

Route::resource('produccion/{prod}/insert', 'ProduccionController@insert');
Route::post('adjust',[
    'as' => 'produccion.adjust',
    'uses' => 'ProduccionController@adjust'
]);
Route::get('produccion/{id}/create', 'ProduccionController@createProd');
Route::post('pass',[
    'as' => 'produccion.pass',
    'uses' => 'ProduccionController@pass'
]);
post('/reqDepUpd', 'ProduccionController@reqDepUpd');
post('/reqUpd', 'ProduccionController@req_upd');
post('/checkDep', 'ProduccionController@checkDep');
post('/storeProd', 'ProduccionController@storeProd');
Route::get('/verProduccion/{id}', 'ProduccionController@verProduccion');
Route::get('/Producciones/reporte/{fecha}',[
    'as' => 'producciones.reporte',
    'uses' => 'ProduccionController@reporte'
]);
Route::get('/Produccion/reporte/{id}',[
    'as' => 'produccion.reporte',
    'uses' => 'ProduccionController@reporteProduccion'
]);
Route::resource('produccion','ProduccionController');


post('/addDependencia', 'DependenciaController@addDependencia');
Route::resource('dependencia','DependenciaController');

Route::resource('aumento','AumentoController');

Route::resource('miscelaneo','MiscelaneoController');

Route::resource('costofijo','CostoFijoController');

Route::resource('produccionmes','ProduccionmesController');

Route::get('cuentaxpagar/view/{id}',[
    'as' => 'cuentaxpagar.view',
    'uses' => 'CtaxPagarController@view'
]);
Route::resource('cuentaxpagar','CtaxPagarController');

Route::get('cuentaxcobrar/view/{id}',[
    'as' => 'cuentaxcobrar.view',
    'uses' => 'CtaxCobrarController@view'
]);
Route::resource('cuentaxcobrar','CtaxCobrarController');

Route::post('caja/abrir',[
    'as' => 'caja.abrir',
    'uses' => 'CajaBancoController@abrir'
]);
Route::get('caja/volverfecha/{entidad}',[
    'as' => 'caja.volverfecha',
    'uses' => 'CajaBancoController@volverfecha'
]);
Route::get('caja/cerrar/{entidad}/{fecha}', [
	'as' => 'caja.cerrarcaja',
	'uses' => 'CajaBancoController@cerrarcaja'
]);
Route::get('caja/confirmar/{entidad}/{fecha}', [
	'as' => 'caja.confirmarcierre',
	'uses' => 'CajaBancoController@confirmarcierre'
]);
Route::get('caja/cierre/{entidad}/{fecha}', [
	'as' => 'caja.vercierre',
	'uses' => 'CajaBancoController@vercierre'
]);
Route::get('caja/reporte/{entidad}/{fecha}', [
	'as' => 'caja.reporte',
	'uses' => 'CajaBancoController@reporte'
]);
Route::get('caja/transferir/{entidad}/{fecha}', [
    'as' => 'caja.transferir',
    'uses' => 'CajaBancoController@transferir'
]);
Route::post('maketransfer',[
    'as' => 'caja.maketransfer',
    'uses' => 'CajaBancoController@maketransfer'
]);
Route::get('caja/entradaForm/{entidad}/{fecha}', [
    'as' => 'caja.entradaForm',
    'uses' => 'CajaBancoController@entradaForm'
]);
Route::get('caja/salidaForm/{entidad}/{fecha}', [
    'as' => 'caja.salidaForm',
    'uses' => 'CajaBancoController@salidaForm'
]);
Route::post('caja/generarEntrada', [
    'as' => 'caja.generarEntrada',
    'uses' => 'CajaBancoController@generarEntrada'
]);
Route::post('caja/generarSalida', [
    'as' => 'caja.generarSalida',
    'uses' => 'CajaBancoController@generarSalida'
]);
Route::resource('caja','CajaBancoController');
post('/getDisponible', 'CajaBancoController@getDisponible');
Route::post('venta/facturar', [
    'as' => 'venta.facturar',
    'uses' => 'VentaController@facturar'
]);
Route::get('venta/revertir/{factura}', [
    'as' => 'venta.revertir',
    'uses' => 'VentaController@revertir'
]);
Route::get('/venta/reporte/{factura_o_mensual}/{atributo}',[
    'as' => 'venta.reporte',
    'uses' => 'VentaController@reporte'
]);
Route::resource('venta','VentaController');

Route::resource('cliente','ClienteController');

Route::resource('banco','BancoController');

Route::post('ajustes/reiniciar-base-de-datos', [
    'as' => 'ajustes.reiniciarDB',
    'uses' => 'AjusteController@reiniciarDB'
]);
Route::post('ajustes/iniciar', [
    'as' => 'ajustes.iniciar',
    'uses' => 'AjusteController@iniciar'
]);
Route::get('ajustes/inventario/{target}/{id}', [
    'as' => 'ajustes.inventario',
    'uses' => 'AjusteController@inventario'
]);
Route::post('ajustes/setinventario', [
    'as' => 'ajustes.setinventario',
    'uses' => 'AjusteController@setinventario'
]);
Route::resource('ajustes','AjusteController');

app/salario.php
<?php

namespace gavca;

use Illuminate\Database\Eloquent\Model;

class salario extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'salarios';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['sal_mensual','salario_integral','unidad_tributaria','cant_cesta_ticket'];
}

app/Http/Controllers/SalarioController.php
<?php

namespace gavca\Http\Controllers;

use Illuminate\Http\Request;

use gavca\salario;
use gavca\aumento;
use gavca\Http\Requests;
use gavca\Http\Requests\SalarioUpdateRequest;
use gavca\Http\Requests\SalarioCreateRequest;
use gavca\Http\Controllers\Controller;

class SalarioController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $salarios = salario::All();
        $aumentos = aumento::All();
        return view('salario.index',compact('salarios','aumentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * GUARDAR EL SALARIO INTEGRAL EN DB
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeSalario(SalarioCreateRequest $request)
    {
        //retorna por post
        if ($request->isMethod('post')){  
           
            $salario_integral = $request->input('salario');

            salario::where('id', 1)
              ->update(['salario_integral' => $salario_integral]);

            return response()->json(['response' => array('message' => 'El salario  se ha actualizado')]);      
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $salario = salario::find($id);
        $aumentos = aumento::All(); 
        return view('salario.edit',compact('salario','aumentos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SalarioUpdateRequest $request, $id)
    {
        $salario = salario::find($id);
        $salario->fill($request->all());
        $salario->save();

        $sal_cargado = $request['sal_mensual'];
        $aumentos = aumento::All(); 
        foreach($aumentos as $aumento)  
        {
            $aumento_escalar = ($aumento->aum_aumento * 0.01) + 1;
            $sal_cargado *= $aumento_escalar; 
        }        
        $sal_diario = $sal_cargado/20;
        $bono_vac_diario = $sal_diario*15/12/30;
        $vac_diario = $sal_diario*21/12/30;
        $bon_fin_diario = $sal_diario*30/12/30;
        $c_tick_diario = ($request['unidad_tributaria']*$request['cant_cesta_ticket']);
        $pres_diario = $sal_diario*5/12/30;
        $salario_integral = $sal_diario+$bono_vac_diario+$vac_diario+$bon_fin_diario+$c_tick_diario+$pres_diario;
        salario::where('id', 1)
              ->update(['salario_integral' => $salario_integral]);

        return redirect('/salario/1/edit')->with('message','Salario y unidad tributaria actualizados exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/salario/forms/rec.blade.php
<div class="content">
<div class="form-group">
	<div class="row margenBotSm">	
		<div class="col-xs-12 col-md-2">
		    {!!Form::label('Nombre de receta: ')!!}			
		</div>
		<div class="col-xs-12 col-md-5">		    
			{!!Form::text('rec_nombre',null,['class'=>'form-control input-lg','placeholder'=>'Ingresa el nombre de la receta'])!!}
		</div>
    </div>
    <div class="row margenBotSm">
    	<div class="col-md-2 col-xs-12">
		    {!!Form::label('¿La receta estará activa al momento de su creación? ')!!}		
		</div>
		<div class="col-md-5 col-xs-12">		    
			{!!Form::select('rec_activo', ['si' => 'Sí', 'no' => 'No'], null, ['placeholder' => 'Escoje si la receta estará activa...'])!!}
		</div>	 		
    </div>
    <div class="row margenBotSm">
    	<div class="col-md-2 col-xs-12">
		    {!!Form::label('Cantidad de producción')!!}		
		</div>
		<div class="col-md-5 col-xs-12">		    
			{!!Form::number('rec_produccion',null,['class'=>'form-control','placeholder'=>'Ingresa la cantidad de producción'])!!}
		</div>	 		
    </div>
</div>
</div>

resources/views/salario/forms/recupd.blade.php
<div class="content">
<div class="form-group">
	{!!Form::model($salario,['route'=>['salario.update',$salario->id],'method'=>'put'])!!}
	<div class="row margenBotSm">	

		
		<div class="col-md-4 col-xs-12 margenBotSm">
			<div class="col-xs-12 col-md-6">
		    	{!!Form::label('Salario base mensual: ')!!}			
			</div>
			<div class="col-xs-12 col-md-6">		    
				{!!Form::text('sal_mensual',null,['class'=>'form-control','placeholder'=>'Ej:425,200.00'])!!}
			</div>
		</div>
		<div class="col-md-4 col-xs-12 margenBotSm">
			<div class="col-xs-12 col-md-6">
			    {!!Form::label('Unidad Tributaria: ')!!}			
			</div>
			<div class="col-xs-12 col-md-6">		    
				{!!Form::number('unidad_tributaria',null,['class'=>'form-control','placeholder'=>'Ingresa el salario base mensual'])!!}
			</div>
		</div>
		<div class="col-md-4 col-xs-12 margenBotSm">
			<div class="col-xs-12 col-md-6">
			    {!!Form::label('Cantidad de Unidades Tributarias de cesta ticket por día trabajado: ')!!}			
			</div>
			<div class="col-xs-12 col-md-6">		    
				{!!Form::number('cant_cesta_ticket',null,['class'=>'form-control','placeholder'=>'Ingresa la cantidad de unidades tributarias en cesta ticket por día trabajado'])!!}
			</div>
		</div>
	</div>
	<div class="row margenBotLg">
		<div class="col-md-2"></div>
		<?php if(Auth::user()->privilegio == "admin" || Auth::user()->privilegio == "tipo1") { ?>
		<div class="col-md-4 col-xs-12">
			{!!Form::submit('Actualizar',['class'=>'btn btn-success btn-block'])!!}
		</div>
		<?php } ?>
		<div class="col-md-4 col-xs-12">
			<a href="/salario" class="btn btn-success btn-block">Volver a Cálculo de Salarios</a>
		</div>
	</div>
		
	{!!Form::close()!!}	

		
    
    <div class="row">	
    	<?php if(Auth::user()->privilegio == "admin" || Auth::user()->privilegio == "tipo1") { ?>
		<div class="col-md-6 col-xs-12">
			{!!link_to_route('aumento.create', $title = 'Registrar un nuevo aumento',null, $attributes = ['class'=>'btn btn-primary btn-sm'])!!}
		</div>
		<?php } ?>
	</div>
    <table class="table table-bordered">
		<thead>
			<th>Descripción del aumento</th>
			<th>Porcentaje sobre la base del aumento</th>
			<th>Operación</th>
		</thead>
		<tbody>
			@foreach($aumentos as $aumento)
			<tr>
				<td>{{$aumento->aum_descripcion}}</td>
				<td>{{$aumento->aum_aumento}}%</td>
				<td>
					{!!Form::open(['route'=>['aumento.destroy',$aumento->id],'method'=>'DELETE'])!!}
						<?php if(Auth::user()->privilegio == "admin" || Auth::user()->privilegio == "tipo1") { ?>
						<div class="btn-group">
						{!!link_to_route('aumento.edit', $title = 'Editar',$parameters = $aumento->id, $attributes = ['class'=>'btn btn-primary btn-sm'])!!}
						{!!Form::submit('Eliminar',['class'=>'btn btn-danger btn-sm'])!!}
						</div>
						<?php } ?>
					{!!Form::close()!!}
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
</div>
</div>