app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'FrontController@index');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::resource('usuario','UsuarioController');

Route::get('/trash/{id}',[
    'as' => 'receta.trash',
    'uses' => 'recetaController@trash'
]);
Route::resource('receta/view_trash', 'recetaController@view_trash');
Route::resource('receta','recetaController');

post('/getIngrediente', 'IngredienteController@getIngrediente');
post('/addIngrediente', 'IngredienteController@addIngrediente');
post('/addProduct', 'IngredienteController@addProduct');
Route::resource('ingrediente','IngredienteController');

Route::resource('log','LogController');
Route::post('/password/correo-de-recuperacion',[
    'as' => 'log.recover',
    'uses' => 'LogController@recover'
]);

Route::get('admin', 'FrontController@admin');

Route::get('logout', 'LogController@logout');


post('/getParam', 'ParametroController@getParam');
Route::resource('parametro','ParametroController');

Route::resource('insumo','InsumoController');

Route::resource('insumousado','InsumoUsadoController');

post('/storeSalario', 'SalarioController@storeSalario');
Route::resource('salario','SalarioController');

post('/getProveedor', 'ProveedorController@getProveedor');
post('/searchProveedor', 'ProveedorController@searchProveedor');
post('/storeProveedor', 'ProveedorController@storeProveedor');
Route::resource('proveedor','ProveedorController');

Route::get('/compra/trash/{id}',[
    'as' => 'compra.trash',
    'uses' => 'CompraController@trash'
]);
Route::resource('compra/view_trash', 'CompraController@view_trash');
Route::post('/compra/pass',[
    'as' => 'compra.pass',
    'uses' => 'CompraController@pass'
]);
Route::get('/compra/reporte/{factura_o_mensual}/{fecha?}/{factura?}',[
    'as' => 'compra.reporte',
    'uses' => 'CompraController@reporte'
]);

post('/checkCode', 'CompraController@checkCode');
post('/createParam', 'CompraController@createParam');
Route::resource('compra','CompraController');

post('/createMP', 'MateriaPrimaController@createMP');
Route::resource('materiaprima/insert', 'MateriaPrimaController@insert');
/*
Route::get('/materiaprima/reporte/{fecha_caja}',[
    'as' => 'materiaprima.reporte',
    'uses' => 'MateriaPrimaController@reporte'
]);
*/
Route::resource('materiaprima', 'MateriaPrimaController');

/*
Route::get('/listCardexMP', 'CardexMPController@listCardexMP');
Route::get('/listCardexPA', 'CardexMPController@listCardexPA');
Route::get('/listCardexPB', 'CardexMPController@listCardexPB');
Route::get('/listCardexPC', 'CardexMPController@listCardexPC');
*/
Route::resource('cardexMP', 'CardexMPController');
Route::get('/cardex/reporte/{fecha}/{item}',[
    'as' => 'cardexmp.reporte',
    'uses' => 'CardexMPController@reporte'
]);


Route::get('/InventarioPA', 'InventarioController@InventarioPA');
Route::get('/InventarioPB', 'InventarioController@InventarioPB');
Route::get('/InventarioPC', 'InventarioController@InventarioPC');

Route::get('/inventario/reporte/{fecha_caja}/{inventario}',[
    'as' => 'inventario.reporte',
    'uses' => 'InventarioController@reporte'
]);
Route::get('/cardexProduccion/reporte/{fecha}/{etapa}/{receta}',[
    'as' => 'produccion.reporteCardex',
    'uses' => 'ProduccionController@reporteCardex'
]);

post('/guardarCostos', 'ProduccionController@guardarCostos');

Route::resource('produccion/{prod}/insert', 'ProduccionController@insert');
Route::post('adjust',[
    'as' => 'produccion.adjust',
    'uses' => 'ProduccionController@adjust'
]);
Route::get('produccion/{id}/create', 'ProduccionController@createProd');
Route::post('pass',[
    'as' => 'produccion.pass',
    'uses' => 'ProduccionController@pass'
]);
post('/reqDepUpd', 'ProduccionController@reqDepUpd');
post('/reqUpd', 'ProduccionController@req_upd');
post('/checkDep', 'ProduccionController@checkDep');
post('/storeProd', 'ProduccionController@storeProd');
Route::get('/verProduccion/{id}', 'ProduccionController@verProduccion');
Route::get('/Producciones/reporte/{fecha}',[
    'as' => 'producciones.reporte',
    'uses' => 'ProduccionController@reporte'
]);
Route::get('/Produccion/reporte/{id}',[
    'as' => 'produccion.reporte',
    'uses' => 'ProduccionController@reporteProduccion'
]);
Route::resource('produccion','ProduccionController');


post('/addDependencia', 'DependenciaController@addDependencia');
Route::resource('dependencia','DependenciaController');

Route::resource('aumento','AumentoController');

Route::resource('miscelaneo','MiscelaneoController');

Route::resource('costofijo','CostoFijoController');

Route::resource('produccionmes','ProduccionmesController');

Route::get('cuentaxpagar/view/{id}',[
    'as' => 'cuentaxpagar.view',
    'uses' => 'CtaxPagarController@view'
]);
Route::resource('cuentaxpagar','CtaxPagarController');

Route::get('cuentaxcobrar/view/{id}',[
    'as' => 'cuentaxcobrar.view',
    'uses' => 'CtaxCobrarController@view'
]);
Route::resource('cuentaxcobrar','CtaxCobrarController');

Route::post('caja/abrir',[
    'as' => 'caja.abrir',
    'uses' => 'CajaBancoController@abrir'
]);
Route::get('caja/volverfecha/{entidad}',[
    'as' => 'caja.volverfecha',
    'uses' => 'CajaBancoController@volverfecha'
]);
Route::get('caja/cerrar/{entidad}/{fecha}', [
	'as' => 'caja.cerrarcaja',
	'uses' => 'CajaBancoController@cerrarcaja'
]);
Route::get('caja/confirmar/{entidad}/{fecha}', [
	'as' => 'caja.confirmarcierre',
	'uses' => 'CajaBancoController@confirmarcierre'
]);
Route::get('caja/cierre/{entidad}/{fecha}', [
	'as' => 'caja.vercierre',
	'uses' => 'CajaBancoController@vercierre'
]);
Route::get('caja/reporte/{entidad}/{fecha}', [
	'as' => 'caja.reporte',
	'uses' => 'CajaBancoController@reporte'
]);
Route::get('caja/transferir/{entidad}/{fecha}', [
    'as' => 'caja.transferir',
    'uses' => 'CajaBancoController@transferir'
]);
Route::post('maketransfer',[
    'as' => 'caja.maketransfer',
    'uses' => 'CajaBancoController@maketransfer'
]);
Route::get('caja/entradaForm/{entidad}/{fecha}', [
    'as' => 'caja.entradaForm',
    'uses' => 'CajaBancoController@entradaForm'
]);
Route::get('caja/salidaForm/{entidad}/{fecha}', [
    'as' => 'caja.salidaForm',
    'uses' => 'CajaBancoController@salidaForm'
]);
Route::post('caja/generarEntrada', [
    'as' => 'caja.generarEntrada',
    'uses' => 'CajaBancoController@generarEntrada'
]);
Route::post('caja/generarSalida', [
    'as' => 'caja.generarSalida',
    'uses' => 'CajaBancoController@generarSalida'
]);
Route::resource('caja','CajaBancoController');
post('/getDisponible', 'CajaBancoController@getDisponible');
Route::post('venta/facturar', [
    'as' => 'venta.facturar',
    'uses' => 'VentaController@facturar'
]);
Route::get('venta/revertir/{factura}', [
    'as' => 'venta.revertir',
    'uses' => 'VentaController@revertir'
]);
Route::get('/venta/reporte/{factura_o_mensual}/{atributo}',[
    'as' => 'venta.reporte',
    'uses' => 'VentaController@reporte'
]);
Route::resource('venta','VentaController');

Route::resource('cliente','ClienteController');

Route::resource('banco','BancoController');

Route::post('ajustes/reiniciar-base-de-datos', [
    'as' => 'ajustes.reiniciarDB',
    'uses' => 'AjusteController@reiniciarDB'
]);
Route::post('ajustes/iniciar', [
    'as' => 'ajustes.iniciar',
    'uses' => 'AjusteController@iniciar'
]);
Route::get('ajustes/inventario/{target}/{id}', [
    'as' => 'ajustes.inventario',
    'uses' => 'AjusteController@inventario'
]);
Route::post('ajustes/setinventario', [
    'as' => 'ajustes.setinventario',
    'uses' => 'AjusteController@setinventario'
]);
Route::resource('ajustes','AjusteController');

app/materiaprima.php
<?php

namespace gavca;

use Illuminate\Database\Eloquent\Model;

class materiaprima extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'materiasprimas';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['mp_codigo', 'mp_cantidad'];
}

app/Http/Controllers/MateriaPrimaController.php
<?php

namespace gavca\Http\Controllers;

use Illuminate\Http\Request;

use DB;
use gavca\materiaprima;
use gavca\parametro;
use gavca\cajabanco;
use gavca\Http\Requests;
use gavca\Http\Controllers\Controller;

class MateriaPrimaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        
    }
    /*PARA PRACTICIDAD AL ADMINISTRADOR SE LE PERMITIRÁ INSERTAR DATA DIRECTAMENTE EN BASE DE DATOS*/
    /*
    TOMA VALORES DE DOS TABLAS DISTINTAS, LA PRIMERA TABLA TIENE DATOS DE MATERIAS PRIMAS QUE ESTAN REGISTRADAS COMO PARÁMETROS, POR LO QUE SÓLO SE NECESITA SABER SU CANTIDAD, LA SEGUNDA TABLA TIENE DATOS DE MATERIAS PRIMAS QUE SE ACABAN DE CREAR, POR LO TANTO SE DEBEN CREAR LOS PARAMETROS TAMBIÉN.
    */
    public function insert()
    {
        /*lista solo las materias primas existentes*/
        /*
        $existentes = DB::table('parametros')
            ->leftJoin('materiasprimas', 'parametros.par_codigo', '=', 'materiasprimas.mp_codigo')
            ->whereNotNull('materiasprimas.mp_codigo')
            ->get();
        */
        /*lista todos los parametros*/
        $existentes = parametro::All();
        //return $existentes;
        return view('materiaprima.insert',compact('existentes'));
    }
    /*REVISA SI LA MP EXISTE EN DB, SI EXISTE ACTUALIZA LA EXISTENCIA SUMANDOLA, SI NO CREA EL MP*/
    public function createMP(Request $request)
    {
        //retorna por post
        if ($request->isMethod('post')){  
            
            $mp_codigo = $request->input('mp_codigo');
            
            $par = materiaprima::where('mp_codigo', $mp_codigo)->first();

            if($par == null){
                //crea
                materiaprima::create([
                'mp_codigo' => $request['mp_codigo'],
                'mp_cantidad' => $request['mp_cantidad'],           
                ]);
                return response()->json(['response' => array('message' => 'creado')]);
            }else{
                //actualiza
                $ncantidad = $request['mp_cantidad']+$par->mp_cantidad;
                $request['mp_cantidad'] = $ncantidad;
                $materiaprima = materiaprima::find($par->id);
                $materiaprima->fill($request->all());
                $materiaprima->save();

                return response()->json(['response' => array('message' => 'actualizado')]);
            }

            //muestra confirmación en formato json en el navegador
            return response()->json(['response' => array(
                'message' => 'Stored'
            )]);  

        }

    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fecha_caja_actual = cajabanco::where('cb_activo',1)->latest()->first()->cb_fecha;
        $fecha_caja_actual = date("Y-m-d", strtotime($fecha_caja_actual));
        $materiasprimas = materiaprima::leftJoin('parametros', 'parametros.par_codigo', '=', 'materiasprimas.mp_codigo')
                ->orderBy('parametros.par_nombre','asc')
                ->select('materiasprimas.mp_codigo','parametros.par_nombre','parametros.par_unidad','materiasprimas.mp_cantidad','materiasprimas.updated_at')
                ->paginate(15);

        return view('materiaprima.index',compact('materiasprimas','fecha_caja_actual'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //INSERTA VALORES DIRECTAMENTE EN MATERIA PRIMA

        //para las materias primas ya existentes en parámetros
        if(isset($request["ex_nombre"])){
            foreach ($request["ex_nombre"] as $i => $nombre) {
                $codigo = parametro::where('par_nombre',$nombre)->first()->par_codigo;
                $existencia = materiaprima::where('mp_codigo',$codigo)->first();
                if($existencia === null){
                    materiaprima::create([
                        'mp_codigo' => $codigo,
                        'mp_cantidad' => $request['ex_cantidad'][$i],           
                    ]);
                }else{
                    DB::table('materiasprimas') ->where('mp_codigo', $codigo) ->update([
                        'mp_codigo' => $codigo,
                        'mp_cantidad' => $request['ex_cantidad'][$i],
                    ]);
                }                
            }
        }
        
        //para cada materia prima no existente ni en parámetros ni en materiasprimas
        if(isset($request["noex_nombre"])){
            foreach ($request["noex_nombre"] as $key => $nombre) {
                //genero el código para cada parametro
                $n = 0;
                //itero para buscar el numero
                for ($i=0; $i < 99999; $i++) { 
                    if($request['noex_perecedero'][$key] == 'si')
                        $pattern = "MP";
                    else
                        $pattern = "MI";
                    //cuento digitos
                    $n = 0; 
                    $floor = $i;           
                    do{
                        $floor = floor($floor / 10);
                        $n++;
                    } while ($floor > 0);
                    
                    //segun la cantidad de numeros agrego ceros para completar 5 cifras
                    $limit = 5-$n;
                    //return $limit;
                    for ($j=0; $j < $limit; $j++) { 
                        $pattern = $pattern."0";
                    }            
                    //concateno el patron con el numero
                    $code = $pattern.$i;  
                    //si no hay ningun numero como este registrado sal del loop y registre
                    $parametro = parametro::where('par_codigo', '=', $code)->first();

                    if ($parametro === null) {
                        break;
                    }
                    
                }

                parametro::create([
                    'par_codigo' => $code,
                    'par_nombre' => $request['noex_nombre'][$key],
                    'par_unidad' => $request['noex_unidad'][$key],
                    'par_costo' => $request['noex_costo'][$key],
                    'par_observacion' => "",
                ]);
                materiaprima::create([
                    'mp_codigo' => $code,
                    'mp_cantidad' => $request['noex_cantidad'][$key],           
                ]);
            }
        }
        return redirect('/materiaprima')->with('message','Existencias en materias primas actualizadas exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/materiaprima/index.blade.php
@extends('layouts.admin')

@section('content')
	<div class="materiasprimas">
	@include('alerts.success')
		<h2 class="form-signin-heading" style="display: inline-block; margin-right: 50px;">Inventario de Materias Primas</h2>
		<?php if(Auth::user()->privilegio == 'admin'){ ?>
			<!--<a href="/materiaprima/insert" class='btn btn-primary btn-sm'>Ajustar Inventario de Materias Primas</a>-->
		<?php } ?>
		{!!link_to_route('inventario.reporte', $title = 'Generar reporte', array($fecha = $fecha_caja_actual, $inventario='Materia Prima'), $attributes = ['class'=>'btn btn-primary','id'=>'btn_reporte'])!!}
		<table class="table">
			<thead>
				<th>Código</th>
				<th>Materia Prima</th>
				<th>Unidad</th>
				<th>Cantidad</th>
				<th>Ultima Modificación</th>
				<th>Cardex</th>
			</thead>
		@foreach($materiasprimas as $materiaprima)
			<tbody>
				<td>{{$materiaprima->mp_codigo}}</td>
				<td>{{$materiaprima->par_nombre}}</td>
				<td>{{$materiaprima->par_unidad}}</td>	
				
				<td>{{$materiaprima->mp_cantidad}}</td>
				<td>{{date("d/m/Y", strtotime($materiaprima->updated_at))}}</td>
				<td>
					<div class="btn-group">
						
						{!!link_to_route('cardexMP.show', $title = 'Ver Cardex', $parameters = $materiaprima->mp_codigo, $attributes = ['class'=>'btn btn-primary btn-xs'])!!}					
					</div>
				</td>
			</tbody>
		@endforeach
		</table>

		
			
	</div>
	{!!$materiasprimas->render()!!}
@endsection

resources/views/materiaprima/insert.blade.php
@extends('layouts.admin')

@section('content')
	{!!Form::open(['route'=>'materiaprima.store','method'=>'POST'])!!}
	<div class="materiasprimas">
	@include('alerts.success')
		<h2 class="form-signin-heading margenBotLg">Ajuste de Existencia de Materias Primas</h2>
		<h3>Selecciona un producto para editar su inventario</h3>
		<table class="table" id="existentes">
			<thead>
				<th>Materia Prima</th>
				<th>Cantidad</th>
				<th>Operación</th>
			</thead>	
		
		</table>
		<div class="row">
			<div class="col-md-3">
				<select id="existente" class="form-control">
					<option diabled selected>Selecciona una M.P.</option>
					@foreach($existentes as $existente)
					<option value="{{$existente->par_nombre}}">{{$existente->par_nombre}}</option>
					@endforeach
				</select>
			</div>
			<div class="col-md-3"><a href="#" id="insertar-existente" class='btn btn-primary btn-sm margenBotLg'>Listar Producto</a></div>
		</div>
		
		
		<div class="row">
			<div class="col-md-12">			
				<h3>Inserta productos directamente en base de datos creandolos desde cero e introduciendo sus cantidades</h3>
			</div>		
		</div>
		
		<table class="table" id="nuevos">
			<thead>
				<th>Materia Prima</th>
				<th>Unidad</th>
				<th>Costo</th>
				<th>Cantidad</th>
				<th>Perecedero</th>
				<th>Operación</th>
			</thead>	
		
		</table>
		<div class="row">
			<div class="col-md-4">
				<a href="#" id="insertar-nuevo" class='btn btn-primary btn-sm margenBotLg'>Insertar Nueva Materia Prima</a>
			</div>			
		</div>	
		
		<div class="row">
			<div class="col-md-4">
				{!!Form::submit('Registrar Ajuste',['class'=>'btn btn-lg btn-success'])!!}
			</div>			
		</div>
		

			
	</div>
	{!!Form::close()!!}
	{!!Html::script('js/jquery.min.js')!!}
	{!!Html::script('js/materiaprima/ajuste.js?8')!!}

@endsection

resources/views/materiaprima/reporte-existencias.blade.php
<!-- pdf.blade.php -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <script type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/estilosPersonalizados.css">
    </head>
    <body>
        <img src="img/gavcalogo.png" alt="logo de la empresa" style="display: inline-block;">
        <h3  style="display: inline-block; vertical-align: middle; margin-left: 5px; width: 500px">
        Reporte de Existencias de materias primas para el mes de {{$mes_long}} del año {{$fecha_formateada->year}}</h3>
        <table class="table">
            <tr>
                <td>Código</td>
                <td>Materia Prima</td>
                <td>Unidad</td>
                <td>Cantidad</td>
                <td>Ultima Modificación</td>
            </tr>
        @foreach($materiasprimas as $materiaprima)
            <tr>
                <td>{{$materiaprima->mp_codigo}}</td>
                <td>{{$materiaprima->par_nombre}}</td>
                <td>{{$materiaprima->par_unidad}}</td>  
                
                <td>{{$materiaprima->mp_cantidad}}</td>
                <td>{{date("Y/m/d", strtotime($materiaprima->updated_at))}}</td>                
            </tr>
        @endforeach
        </table>
     <script src="js/jquery.min.js"></script> 
     <script src="js/bootstrap.min.js"></script> 
    </body>
</html>